### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by heta2609** [mpmc/tvheadend#86]
I use the unofficial packages for RPI on https://tvheadend.org/projects/tvheadend/wiki/AptRepository#Raspberry-Pi-Raspbian-armhf.
 But since a few weeks there is no update on tvheadend any more when I try to update with apt-get ...  . Is there a special reason?

**Comment by mpmc** [comment]
The packages from my apt repo are built using the sources from [tvheadend](https://github.com/tvheadend/tvheadend.git)'s main git repository not from here. 

There have been no updates because there have been no commits as of late. I can only speculate that @perexg (our main dev atm) is extremely busy with other things right now & hasn't got time to work on tvheadend. Or he's taking a well deserved break! I'll leave @perexg to comment further if he so wishes.

Rest assured when there's an update a new package will be pushed out.

**Comment by heta2609** [comment]
Many thanks for the update

**Comment by mpmc** [comment]
closing as resolved!
